### PR TITLE
Add `--language` flag

### PR DESCRIPTION
**Pull request by franciscop**
Allow to pass the language from the command. Defaults to English.

### CODE REVIEW

**Comment by sindresorhus** [comment]
The flag should be `—language` and the default value should be set in the meow options.

**Comment by sindresorhus** [comment]
You also need to update the readme.

**Comment by franciscop** [comment]
A couple of questions:

- Add `-l` as a short flag?
- Add `--all` to the meow options?
- Add `-a` flag for all?

**Comment by sindresorhus** [comment]
I don't think short-flags are necessary here.

**Pull request merged**
