### PR TITLE
added --number flag

### PR DESCRIPTION
**Pull request by vsdaan**
I added in an extra flag which lets you specify a pokedex number and returns that pokemon if specified.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please spend some more time perfecting this PR. Make sure you run `$ npm test` locally.

**Comment by vsdaan** [comment]
It should be fixed now

**Comment by sindresorhus** [comment]
> Please spend some more time perfecting this PR.

Please actually do this.

**Comment by vsdaan** [comment]
afbeelding
npm test runs perfectly fine locally on my pr

**Comment by sindresorhus** [comment]
Just look over your own diff and changes. This is not about the tests since you haven't added any test yourself.

**Pull request closed without merging**
